environment:
  matrix:
    - nodejs_version: ""
platform:
- x64
- x86
cache:
- node_modules
- "%LOCALAPPDATA%\\Yarn"
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- yarn upgrade
test_script:
- yarn test
- yarn start build
build: off
