engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: true
    exclude_fingerprints:
    - 95ea0e6ac034573af69bc979f6dcc0f5
    - 29898bbee6f210eff6477b087ceb11a1
  eslint:
    enabled: true
    config:
      config: .eslintrc.yml
      extensions:
      - .js
      - .vue
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.vue"
  - "**.sass"
  - "**.md"
  - "**.sh"
exclude_paths:
- .vscode
- public
- tests
