engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: true
  eslint:
    # CodeClimate doesn't support eslint-config-vue yet
    enabled: false
    channel: "eslint-3"
    config:
      config: .eslintrc
      extensions:
      - .js
      - .vue
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.vue"
exclude_paths:
- .vscode
- static
- tests
