language: node_js

cache:
  directories:
  - node_modules

node_js: node

sudo: false

matrix:
  fast_finish: true

before_install:
- stty cols 80

install:
- travis_retry npm i

before_script:
- npm t

script:
- npm run build

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash build/deploy.sh
addons:
  code_climate:
    repo_token: d4e9d96b88184c8841c0f11761fe17e51e4f2ee53e07b5204f7049a7f286bd61
