os:
- linux
- osx
language: node_js
node_js: node
cache:
  directories:
  - node_modules
sudo: false
matrix:
  fast_finish: true
before_install:
- npm update && npm prune
install:
- travis_retry npm i
before_script:
- npm start test
script:
- npm start build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_OS_NAME == "linux" && bash build/deploy.sh
- bash <(curl -s https://codecov.io/bash)
- bash build/yarn.sh
addons:
  code_climate:
    repo_token: d4e9d96b88184c8841c0f11761fe17e51e4f2ee53e07b5204f7049a7f286bd61
