language: node_js
cache:
  directories:
  - node_modules
node_js: node
sudo: false
matrix:
  fast_finish: true
before_install:
- npm update && npm prune
install:
- travis_retry npm i
script:
- npm run build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash build/deploy.sh
